apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-db
  labels:
    app: shopping-cart-db 
spec:
  selector:
    app: shopping-cart-db
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: shopping-cart-db 
spec:
  selector:
    matchLabels:
      app: shopping-cart-db
  replicas: 1
  template:
    metadata:
      labels:
        app: shopping-cart-db 
    spec:
      containers:
        - name: shopping-cart-db 
          image: postgres:11.5-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-secrets
                  key: db-name 
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-secrets
                  key: db-username
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-secrets
                  key: db-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: shopping-cart-db 
      volumes:
        - name: shopping-cart-db 
          persistentVolumeClaim:
            claimName: shopping-cart-db-pv-claim